# Generated by Django 5.1.2 on 2024-10-31 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebookpage",
            name="agency_location",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facebookpage",
            name="agency_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facebookpage",
            name="cash_assistance_statement",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facebookpage",
            name="deployment_countries",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="facebookpage",
            name="establishment_date",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
