# Generated by Django 5.1.2 on 2024-10-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("page", "0002_facebookpage_agency_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facebookpage",
            old_name="name",
            new_name="token",
        ),
        migrations.RemoveField(
            model_name="facebookpage",
            name="details",
        ),
    ]
