# Generated by Django 5.1.2 on 2024-10-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_userprofile_is_copied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_copied",
            field=models.BooleanField(default=False),
        ),
    ]
